// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateEmailVerification(ctx context.Context, db DBTX, arg CreateEmailVerificationParams) (EmailVerification, error)
	CreatePasswordReset(ctx context.Context, db DBTX, arg CreatePasswordResetParams) (PasswordReset, error)
	CreateUser(ctx context.Context, db DBTX, arg CreateUserParams) (User, error)
	GetEmailVerificationByToken(ctx context.Context, db DBTX, token string) (EmailVerification, error)
	GetPasswordResetByToken(ctx context.Context, db DBTX, token string) (PasswordReset, error)
	GetUserByEmail(ctx context.Context, db DBTX, email string) (User, error)
	ResetPassword(ctx context.Context, db DBTX, arg ResetPasswordParams) (User, error)
	UpdateLastLogin(ctx context.Context, db DBTX, id pgtype.UUID) (pgtype.UUID, error)
	UpdateUser(ctx context.Context, db DBTX, arg UpdateUserParams) (User, error)
	VerifyEmail(ctx context.Context, db DBTX, id pgtype.UUID) (User, error)
}

var _ Querier = (*Queries)(nil)
