// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateUser(ctx context.Context, db DBTX, arg CreateUserParams) (User, error)
	DeleteUser(ctx context.Context, db DBTX, id pgtype.UUID) (User, error)
	GetUser(ctx context.Context, db DBTX, email string) (User, error)
	ListUsers(ctx context.Context, db DBTX) ([]User, error)
	UpdateUser(ctx context.Context, db DBTX, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
