// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type EmailVerification struct {
	ID        pgtype.UUID      `db:"id" json:"id"`
	UserID    pgtype.UUID      `db:"user_id" json:"user_id"`
	Token     string           `db:"token" json:"token"`
	ExpiresAt pgtype.Timestamp `db:"expires_at" json:"expires_at"`
	CreatedAt pgtype.Timestamp `db:"created_at" json:"created_at"`
}

type PasswordReset struct {
	ID        pgtype.UUID      `db:"id" json:"id"`
	UserID    pgtype.UUID      `db:"user_id" json:"user_id"`
	Token     string           `db:"token" json:"token"`
	ExpiresAt pgtype.Timestamp `db:"expires_at" json:"expires_at"`
	CreatedAt pgtype.Timestamp `db:"created_at" json:"created_at"`
}

type User struct {
	ID           pgtype.UUID      `db:"id" json:"id"`
	Email        string           `db:"email" json:"email"`
	Password     pgtype.Text      `db:"password" json:"password"`
	Level        string           `db:"level" json:"level"`
	GoogleID     pgtype.Text      `db:"google_id" json:"google_id"`
	FullName     pgtype.Text      `db:"full_name" json:"full_name"`
	ProfileImage pgtype.Text      `db:"profile_image" json:"profile_image"`
	IsVerified   pgtype.Bool      `db:"is_verified" json:"is_verified"`
	LastLogin    pgtype.Timestamp `db:"last_login" json:"last_login"`
	CreatedAt    pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamp `db:"updated_at" json:"updated_at"`
	DeletedAt    pgtype.Timestamp `db:"deleted_at" json:"deleted_at"`
}
